package euler;

/**
*
* Each new term in the Fibonacci sequence is generated by adding the previous two terms.
* By starting with 1 and 2, the first 10 terms will be:
* 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
*
* By considering the terms in the Fibonacci sequence whose values do not exceed four million,
* find the sum of the even-valued terms.
*
*/
public class Problem02 {
 public static void main(String[] args) {

   long result = 0;
   long CEILING = 4000000;
   long nMinus2 = 1;
   long nMinus1 = 2;
   long n = nMinus2 + nMinus1;
   result = result += nMinus1;
   while (n <= CEILING) {
     if (n % 2 == 0) {
       result += n;
     }
     nMinus2 = nMinus1;
     nMinus1 = n;
     n = nMinus2 + nMinus1;
   }

   System.out.println("Result = " + result);
 }

}
